### ISSUE TITLE
Conflict between hook factory and renaming hooks

### ISSUE THREAD

**Issue by bushkov** [python-attrs/cattrs#165]
* cattrs version: 1.8.0
* Python version: 3.8.11
* Operating System: macOS 11.5.2

### Description

I am trying to register a hook factory on all `attrs` classes which omits all default values. At the same time for some attributes of some classes I am trying to register a renaming hook.

There is seems to be a conflict between the hook factory and the renaming hooks - having renaming hooks results in hook factory being ignored for classes on which we have to do renaming.

### What I Did

The following code
```python
@attr.s
class A:
    name_1: int = attr.ib()
    omit: Optional[int] = attr.ib(default=None)


converter = cattr.GenConverter()

converter.register_unstructure_hook_factory(
    has,
    lambda cls: make_dict_unstructure_fn(
        cls,
        converter,
        **{
            attribute.name: override(omit_if_default=True)
            for attribute in fields(cls)
        }
    ),
)

unstructure_renaming_hook = make_dict_unstructure_fn(
    A, converter, name_1=override(rename="name_2")
)
structure_renaming_hook = make_dict_structure_fn(
    A, converter, name_1=override(rename="name_2")
)
converter.register_unstructure_hook(A, unstructure_renaming_hook)
converter.register_structure_hook(A, structure_renaming_hook)


def test():
    assert converter.unstructure(A(1)) == {"name_2": 1}
```
produces:
```
AssertionError: assert {'name_2': 1, 'omit': None} == {'name_2': 1}
```
If I remove the renaming hooks, then the test passes.

**Comment by Tinche** [comment]
Ok to close this?

**Comment by bushkov** [comment]
> Ok to close this?

Yes, you can close it.
