### ISSUE TITLE
GenConverter fails to structure when init=False attributes are present

### ISSUE THREAD

**Issue by bushkov** [python-attrs/cattrs#166]
* cattrs version: 1.8.0
* Python version: 3.8.11
* Operating System: macOS 11.5.2

### Description

I am trying to structure an `attrs` class that contains an attribute which shouldn't be initialized on instance creation. When I use `Converter`, the structuring works fine, but when I use `GenConverter` it fails.

### What I Did

Here is a  simple example that fails:

```python
import attr
import cattr


c = cattr.GenConverter()

@attr.s
class A:
    x: int = attr.ib()
    y: int = attr.ib(init=False)


d = {"x": 0}

c.structure(d, A)
```

It fails with:
```
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    c.structure(d, A)
  File "cattr/converters.py", line 294, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "<cattrs generated structure __main__.A>", line 4, in structure_A
KeyError: 'y'
```

On a related note it's not clear to me from the documentation in which situation one should prefer to use `Converter` and in which situation one should prefer `GenConverter`. In particular the following points are unclear:
> GenConverter differs from the old cattr.Converter in the following ways:
> * structuring and unstructuring of attrs classes is slower the first time, but faster every subsequent time
> * structuring and unstructuring can be customized
> * support for easy overriding collection unstructuring

By 'faster every subsequent time' does it mean that `GenConverter` is faster than `Converter` or does it mean that it's getting faster with every structure/unstructure, but not faster than `Converter`?

About 'structuring and unstructuring can be customized' and `support for easy overriding collection unstructuring`, it would be helpful to have some concrete examples showing what one can do with `GenConverter` which cannot be done with `Converter`.

**Comment by Tinche** [comment]
Ok to close this?

**Comment by bushkov** [comment]
@Tinche yes, it's ok to close this one.

**Comment by Tinche** [comment]
@artem30801 You're right, it doesn't work for structuring. It's even documented here: https://cattrs.readthedocs.io/en/latest/customizing.html#omit

That said, I don't remember why it doesn't work for structuring in the first place. I guess no one asked for it yet. I can add it in the next couple of days.

**Comment by otaj** [comment]
Hi @Tinche , would it be possible to release a new version with this fix released? Thanks!

**Comment by otaj** [comment]
I just noticed, that there already is a version of 1.9.0, just not yet released to PyPI. Can you please release it there? Thanks!

**Comment by Tinche** [comment]
1.9.0 hasn't been released yet at all. I can get around to it over the weekend.

**Comment by otaj** [comment]
Oh, right, it just has a version in `pyproject.toml`. If you could release it over the weekend (or just some minor version with patch for this included), that would be awesome! Thank you!

**Comment by Tinche** [comment]
@otaj Released!
