### ISSUE TITLE
structure/unstructure doesn't support generic nested attrs objects

### ISSUE THREAD

**Issue by Savlik** [python-attrs/cattrs#170]
* cattrs version: 1.8.0
* Python version: 3.8.10
* Operating System: Linux

### Description

I have two nested attrs objects, the outer one has the attribute as generic. I would expect it would unstructure both as if the attribute was specified directly. Am I doing something wrong, or is it a bug? Is there a way to accomplish this? Thanks

### What I Did

```python
from typing import TypeVar, Generic
from cattr import GenConverter
from attr import attrs

T = TypeVar("T")
c = GenConverter()

@attrs(auto_attribs=True)
class Inner():
    a: int

@attrs(auto_attribs=True)
class Outer(Generic[T]):
    inner: T

initial = Outer[Inner](Inner(1))
raw = c.unstructure(initial, Outer[Inner])
assert raw == {"inner": {"a": 1}}
#      ^^^ getting {'inner': Inner(a=1)} instead
new = c.structure(raw, Outer[Inner])
assert initial == new
```

**Comment by Tinche** [comment]
@Savlik Looks like a bug. I'll see about getting it fixed for the next release!

**Comment by wakemaster39** [comment]
I put some code into #172 for this. 

Its a little rough having to use the `inspect` module to detect the signature, but this allows deeply nested things to work.

**Comment by MicaelJarniac** [comment]
I was having this issue today, and installing the latest (unreleased) version of `cattrs` solved it!

Here are the error messages:

```
  File "/test.py", line 2, in from_bson
    return converter_bson.structure(b, cls)
  File "/venv/lib/python3.8/site-packages/cattr/converters.py", line 294, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "/venv/lib/python3.8/site-packages/cattr/dispatch.py", line 49, in _dispatch
    return self._function_dispatch.dispatch(cl)
  File "/venv/lib/python3.8/site-packages/cattr/dispatch.py", line 126, in dispatch
    return handler(typ)
  File "/venv/lib/python3.8/site-packages/cattr/converters.py", line 733, in gen_structure_attrs_fromdict
    h = make_dict_structure_fn(
  File "/venv/lib/python3.8/site-packages/cattr/gen.py", line 177, in make_dict_structure_fn
    mapping = _generate_mapping(base, mapping)
  File "/venv/lib/python3.8/site-packages/cattr/gen.py", line 156, in _generate_mapping
    return cls(**mapping)
TypeError: __init__() got an unexpected keyword argument 'T'
```

By installing the latest version directly from this repo, this issue was fixed:

```bash
pip install git+git://github.com/python-attrs/cattrs
```

But it's probably better to wait for those fixes to be on a release.

**Comment by Tinche** [comment]
@Savlik I think this is fixed, can we close?

**Comment by Savlik** [comment]
@Tinche It works now. Thanks for the fix, guys.
