### ISSUE TITLE
Literal[...] with more than one item raises exception

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/cattrs#180]
* cattrs version: 1.9.0 (unreleased, installed from GitHub)
* Python version: 3.8.10
* Operating System: Ubuntu running on WSL2 on Windows 10

### Description

The `Literal[...]` type allows for multiple values to be used, like `Literal["one", "two"]`, but `cattr` seems to only support the very first value, and throws an exception when structuring the others.

```py
from typing import Literal, Optional

import attr
import cattr


@attr.s(auto_attribs=True)
class A:
    foo: Optional[Literal["one", "two"]] = None


cattr.structure({}, A)
# A(foo=None)

cattr.structure({"foo": "one"}, A)
# A(foo='one')

cattr.structure({"foo": "two"}, A)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/venv/dev/lib/python3.8/site-packages/cattr/converters.py", line 295, in structure
#     return self._structure_func.dispatch(cl)(obj, cl)
#   File "<cattrs generated structure __main__.A>", line 5, in structure_A
#   File "/venv/dev/lib/python3.8/site-packages/cattr/converters.py", line 526, in _structure_optional
#     return self._structure_func.dispatch(other)(obj, other)
#   File "/venv/dev/lib/python3.8/site-packages/cattr/converters.py", line 404, in _structure_literal
#     raise Exception(f"Literal {type} not equal to {val}")
# Exception: Literal typing.Literal['one', 'two'] not equal to two
```

https://docs.python.org/3/library/typing.html#typing.Literal

This issue has also been reported on https://github.com/python-attrs/cattrs/issues/122#issuecomment-853771560, but since that issue is closed, I decided to open a new one for this.

What I'm currently doing as a work-around is using `Enum`s instead of `Literal`s, since `cattr` has some awesome support for `Enum`s.

**Comment by Tinche** [comment]
This one should be pretty easy, feel like making a PR?

**Comment by MicaelJarniac** [comment]
@playpauseandstop proposed a solution I think and even mentioned opening a PR.
I'm not sure if they're still interested. If they aren't, then I'll give it a try.

**Comment by ErikvdVen** [comment]
@MicaelJarniac we are interested in a solution and since the previous issue is closed, I would suggest opening a PR ;) Would be great!

**Comment by MicaelJarniac** [comment]
I'll begin working on this issue then.
