### ISSUE TITLE
WARNING: cattrs 1.9.0 does not provide the extra 'dev' (when trying to set up dev env)

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/cattrs#181]
* cattrs version: 1.9.0 (from GitHub)
* Python version: 3.9.7
* Operating System: Ubuntu on WSL2 on Windows 10

### Description
I'm trying to follow these instructions to set up a development environment:
https://cattrs.readthedocs.io/en/latest/contributing.html#get-started
```
$ cd cattrs/
$ pip install -e .\[dev\]
```
And this is the output:
```
Obtaining file:///home/micael/projects/cattrs
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
WARNING: cattrs 1.9.0 does not provide the extra 'dev'
Collecting attrs>=20
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Installing collected packages: attrs, cattrs
  Running setup.py develop for cattrs
    ERROR: Command errored out with exit status 1:
     command: /home/micael/projects/cattrs/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/micael/projects/cattrs/setup.py'"'"'; __file__='"'"'/home/micael/projects/cattrs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/micael/projects/cattrs/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/micael/projects/cattrs/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/micael/projects/cattrs/setup.py'"'"'; __file__='"'"'/home/micael/projects/cattrs/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
The line in question is:
```
WARNING: cattrs 1.9.0 does not provide the extra 'dev'
```
I think the docs may be outdated, or I'm doing something wrong.

**Comment by Tinche** [comment]
cattrs uses poetry, so instead just do `poetry install`.

What you're trying to use is a very new pip feature where packages using other build tools (poetry, flit, ...) can be installed in editable mode, but I haven't looked very much into it. (I've seen your error myself before though, I just don't understand it well yet. I don't want to depend on setuptools :)

**Comment by MicaelJarniac** [comment]
Poetry is also giving me trouble :c 
`py-cpuinfo` is having that `ModuleNotFoundError: No module named 'setuptools'` error, and `poetry install -E dev` says that `Extra [dev] is not specified.`.
And when I try to run `pytest` it complains that `ModuleNotFoundError: No module named 'hypothesis'`.

**Comment by MicaelJarniac** [comment]
Nevermind, just created a new venv and now it worked.

**Comment by MicaelJarniac** [comment]
Okay, it worked, but I had to do `poetry update` first. Otherwise, I'd still get the `ModuleNotFoundError: No module named 'setuptools'` error when it tries to install `py-cpuinfo`.

**Comment by MicaelJarniac** [comment]
> Okay, it worked, but I had to do `poetry update` first. Otherwise, I'd still get the `ModuleNotFoundError: No module named 'setuptools'` error when it tries to install `py-cpuinfo`.

Updating `pip`, `setuptools`, and `wheel` on my system's Python seems to have solved this (updating all three of them might not have been necessary).

**Comment by MicaelJarniac** [comment]
> > Okay, it worked, but I had to do `poetry update` first. Otherwise, I'd still get the `ModuleNotFoundError: No module named 'setuptools'` error when it tries to install `py-cpuinfo`.
> 
> Updating `pip`, `setuptools`, and `wheel` on my system's Python seems to have solved this (updating all three of them might not have been necessary).

Or maybe not... It still doesn't seem to work with the current versions, needing a `poetry update` for it to work.

**Comment by MicaelJarniac** [comment]
Do you remember which errors you were getting when trying to `poetry install`? IIRC the only one I was getting was related to that `py-cpuinfo` saying that `ModuleNotFoundError: No module named 'setuptools'`, but this same error appeared multiple times. Other than that, everything seemed to work. And if I did a `poetry update`, then cleaned up the venv, then `poetry install`, it worked.

**Comment by Tinche** [comment]
Yeah, we use Poetry 1.2.0a2 at this time unfortunately. When I was adding Python 3.10 support stable Poetry wasn't working with it so I switched to the alpha.

Groups are a new Poetry mechanism that's supposed to supercede dev dependencies (you're supposed to have a group for dev, and maybe groups for testing, docs, etc).

1.2.0a2 should work though, I use it on a daily basis.

I don't think you can use `pip install -e .` with Poetry and cattrs. So just use Poetry directly. `pip install -e .` working with non-setuptools projects is a very new feature. I have tried it but also got the complaint it wants setuptools installed. Then I got confused since the whole point of Poetry is to get away from setuptools.

**Comment by anthrotype** [comment]
I think the problem was that I was trying to run `poetry install` from within an active venv of mine. I reinstalled poetry 1.2.0a2 and run `poetry install` from outside of the venv, and it worked.

I haven't used poetry yet, it may be better than the traditional venv+setuptools+pip setup, but what I don't like is that it seems to force one into its own very particular workflow. Now I will have to spend an hour or so reading the poetry docs and relearning how to create an environment, install dependencies, run code inside that, etc.

**Comment by anthrotype** [comment]
apologies for the rant, of course you're free to choose whatever build tool you prefer 👍

**Comment by Tinche** [comment]
Ah yes, I understand your complaint and I sympathize. Until a clear winner emerges you'll probably need to be aware of setuptools, flit and Poetry unfortunately, depending on the project. I personally think Poetry is very cool and much more usable than the alternatives, but a lot of sharp edges at this time.

I also think it's valid to run Poetry install from within a virtualenv. But I have only ever run it from within virtualenvs it created.

**Comment by Tinche** [comment]
I'm considering switching to Flit FWIW. Going to close this now though.
