### ISSUE TITLE
Problem with type annotations

### ISSUE THREAD

**Issue by neriusmika** [python-attrs/cattrs#183]
* cattrs version: 1.8.0
* Python version: 3.9.7
* Operating System: Windows 10

### Description

Unstructure is failing when types are annotated inside other type with quotes.
If type annotation is not nested or quotes are not used, then unstructuring succeeds.

### What I Did

```python
from attr import field, frozen
from cattr.preconf.json import make_converter


@frozen
class First:
    arg1: int
    arg2: "Second"
    arg3: tuple["Second", ...] = field(factory=tuple)


@frozen
class Second:
    arg1: str


obj = First(arg1=1, arg2=Second("123"), arg3=(Second("abc"),))

print(obj)

converter = make_converter()
obj_dict = converter.unstructure(obj)

print(obj_dict)
```
#### Output:
```
First(arg1=1, arg2=Second(arg1='123'), arg3=(Second(arg1='abc'),))
{'arg1': 1, 'arg2': {'arg1': '123'}, 'arg3': [Second(arg1='abc')]}  <--- arg2 succeeded, arg3 failed
```
`from __future__ import annotations` doesn't have this problem:
```python
from __future__ import annotations

from attr import field, frozen
from cattr.preconf.json import make_converter


@frozen
class First:
    arg1: int
    arg2: Second
    arg3: tuple[Second, ...] = field(factory=tuple)


@frozen
class Second:
    arg1: str


obj = First(arg1=1, arg2=Second("123"), arg3=(Second("abc"),))

print(obj)

converter = make_converter()
obj_dict = converter.unstructure(obj)

print(obj_dict)
```
#### Output:
```
First(arg1=1, arg2=Second(arg1='123'), arg3=(Second(arg1='abc'),))
{'arg1': 1, 'arg2': {'arg1': '123'}, 'arg3': [{'arg1': 'abc'}]}
```

**Comment by neriusmika** [comment]
I found in #69 that you don't want to support such cases. Closing.

**Comment by Tinche** [comment]
That PR is from 2019, a lot has changed in the mean time. I can take a look at your issue when I get some time.

**Comment by Tinche** [comment]
Actually, very quick: if you change `tuple["Second", ...]` to `"tuple[Second, ...]"`, does it help?

**Comment by neriusmika** [comment]
Yes, it does. But for me, the problem is that those classes that I am using are automatically generated by another library. And there is no difference to replace the quotes or add form \_\_future\_\_ import annotations. Still, manual work is involved :)
