### ISSUE TITLE
Broken reference to Travis CI

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/cattrs#188]
> 3. The pull request should work for all supported Python versions. Check
   https://travis-ci.org/Tinche/cattrs/pull_requests
   and make sure that the tests pass for all supported Python versions.

https://github.com/python-attrs/cattrs/blame/main/CONTRIBUTING.rst#L105

I believe there are a couple of things wrong with this URL.
First, it's using `travis-ci.org`, which is supposedly deprecated and should be replaced by `travis-ci.com`, with some other changes to make it work:
https://app.travis-ci.com/github/Tinche/cattrs/pull_requests
But then, this still points to the old repo, last updated 10 months ago, and this new repo, in `python-attrs`, doesn't seem to be on Travis CI.

**Comment by Tinche** [comment]
Ah yeah, we've since switched to GitHub Actions. Need to update the docs.

**Comment by Tinche** [comment]
Fixed, thanks.
