### ISSUE TITLE
can't structure dataclass with PEP563 postponed annotations or forward references

### ISSUE THREAD

**Issue by anthrotype** [python-attrs/cattrs#195]
* cattrs version: 1.8.0
* Python version: 3.10.0
* Operating System: macOS 12.0.1

### Description

I would like to use cattrs with dataclasses (for this project I can't use attrs classes). I get the following errors when I try to structure a dataclass with circular, nested definitions that contain string literals to be post-evaluated (e.g. via `typing.get_type_hints`).
It seems that this currently only works with attrs classes, but not dataclasses.

### What I Did

```python
from __future__ import annotations
from typing import List
from dataclasses import dataclass, field
from cattr import Converter, GenConverter


@dataclass
class Node:
    children: List[Node] = field(default_factory=list)


tree = Node([Node([Node(), Node()]), Node()])

c = GenConverter()
data = c.unstructure(tree)
# Raises: NotAnAttrsClassError: <class '__main__.Node'> is not an attrs-decorated class.
c.structure(data, Node)


c = Converter()
data = c.unstructure(tree)
# Raises: StructureHandlerNotFoundError: Unsupported type: List[Node]. Register a structure hook for it.
c.structure(data, Node)
```

If I remove `from __future__ import annotations` and type the nested `children: List["Node"]` I get this other error:

```
StructureHandlerNotFoundError: Unsupported type: ForwardRef('Node'). Register a structure hook for it.
```

**Comment by anthrotype** [comment]
Note the same happens with the newly released cattrs 1.9.0

**Comment by Tinche** [comment]
Hm, for attrs classes I use `attr.resolve_types`, and that doesn't exist for dataclasses. I can try using `typing.get_type_hints` directly, but that won't cover some of the use cases (like when you need to resolve them yourself, in a special way).

**Comment by anthrotype** [comment]
> using typing.get_type_hints directly

yeah, I suppose that's the way to go. You can have a `resolve_types` in _compat that delegates to attrs.resolve_types for attrs classes or does the same thing for dataclasses.

> won't cover some of the use cases (like when you need to resolve them yourself, in a special way)

not sure what you mean by that

**Comment by Tinche** [comment]
I just pushed support for this to the main branch, feel free to test it out.

**Comment by anthrotype** [comment]
Thanks, it works now!
