### ISSUE TITLE
make_dict_structure_fn does not work with dataclasses when PEP 563 is active

### ISSUE THREAD

**Issue by aha79** [python-attrs/cattrs#199]
* cattrs version: 1.8.0    (attrs 21.2.0)
* Python version: 3.9.7
* Operating System: Windows 10

### Description

`make_dict_structure_fn` does not seem to work with dataclasses (just with attr classes)

### What I Did

```
from __future__ import annotations
import attr
import dataclasses
import cattr
@dataclasses.dataclass               # <-- this doesnt
#@attr.define(auto_attribs=True)     # <-- this works
class X:
    a: int
    b_: float

converter = cattr.GenConverter()
make_dict_structure_fn(X, converter)   # <--raises NotAnAttrsClassError      <class '__main__.X'> is not an attrs-decorated class.
```

The error occurs in `resolve_types`  in gen-py in this [line](https://github.com/python-attrs/cattrs/blob/bc9432e606177fe10aa3d2d11e715970c92526be/src/cattr/gen.py#L250)

I am not sure if this is intentional behavior or not, but given the line `is_dc = is_dataclass(cl)` in `make_dict_structure_fn` in `gen.py` I guess this might be a bug.

**Comment by Tinche** [comment]
@aha79 Can you try the main branch? This should be fixed but has not yet been released.

**Comment by aha79** [comment]
@Tinche Indeed it works on the main branch. Awesome.
