### ISSUE TITLE
A few syntax sugar ideas

### ISSUE THREAD

**Issue by aldanor** [python-attrs/cattrs#20]
Hi! First, a very neat idea and a neat implementation :)

As I munged with it for a bit, I was wondering if you'd consider a few potential syntactic shortcuts?

1) Registering both hooks at once:

For example, if I want pandas Timedeltas to be serialized/deserialized as strings, I have to do something like

```python
cattr.register_structure_hook(pd.Timedelta, pd.Timedelta)
cattr.register_unstructure_hook(pd.Timedelta, str)
```

This seems like a quite common case (registering both at once), may something like this could work?

```python
cattr.register_hooks(pd.Timedelta, pd.Timedelta, str)
```

2) Same as above, but for attr classes. Also, maybe support passing `attr.asdict` and `attr.astuple` instead of `cattr.{structure,unstructure}_attrs_from{dict,tuple}`? E.g., instead of 

```python
cattr.register_structure_hook(Foo, cattr.structure_attrs_fromtuple)
cattr.register_unstructure_hook(Foo, cattr.unstructure_attrs_fromtuple)
```

maybe you could also just do

```python
cattr.register_hooks(Foo, attr.astuple)
```

3) Registering hooks for attr types. Maybe allow embedding conversion information into the types themselves? E.g. via some predefined dunder magics, or decorators? Hypothetically, kind of like:

```python
@attr.s(slots=True)
class Foo:
    a: int = attr.ib()
    
    __cattr__ = attr.astuple  # or separate __structure__ / __unstructure__
```

or maybe even

```python
@cattr.s(slots=True, cattr=attr.astuple)  # or structure= / unstructure=
class Foo:
    a: int = attr.ib()
```

This one's may be a bit too much, but I thought I'd share all my somewhat random thoughts anyhow :)

Thanks!

**Comment by aldanor** [comment]
2.5) I've noticed the example in 2) doesn't actually work at all, since `cattr.unstructure_attrs_fromtuple` doesn't even exist at all. I guess you currently have to do something like this:

```python
cattr.global_converter.register_unstructure_hook(
    Foo,
    cattr.global_converter.unstructure_attrs_astuple
)
```

whereas it could be at least

```python
cattr.register_unstructure_hook(Foo, cattr.unstructure_attrs_astuple)
```

or, as suggested above,

```python
cattr.register_unstructure_hook(Foo, attr.astuple)
```

**Comment by leesdolphin** [comment]
I'd like to add another suggestion, Can the `register_<>_hook` be used as a decorator.

```
@cattr.register_structure_hook(MyClass)
def parse_my_class(value, _type):
  ...
```

**Comment by Tinche** [comment]
Thanks for the ideas. There's a new API for validation and customization coming in 24.1. Going to close this as stale though, the OP is 6 years old almost ;)
