### ISSUE TITLE
Structuring with registered hook for Base and Derived class does not work properly with PEP 563 

### ISSUE THREAD

**Issue by aha79** [python-attrs/cattrs#200]
* cattrs version: 1.8.0    (attrs 21.2.0)
* Python version: 3.9.7
* Operating System: Windows 10

### Description

When registering a hook for Base class and Derived class 
a StructureHandlerNotFoundError  exception is obtained from call `structure`.

This only happens if PEP 563 is active *and* Base is registered before Derived.

If one registers Derived before Base it works. 

If one turns off PEP 563 it also works.

### What I Did

```
from __future__ import annotations

import cattr
import attr
from cattr.gen import *


@attr.define(auto_attribs=True)
class Base:
    a: int
    b: float

@attr.define(auto_attribs=True)
class Derived(Base):
    zz: int


converter = cattr.Converter()

converter.register_unstructure_hook(Base, make_dict_unstructure_fn(Base, converter)) 
converter.register_structure_hook(Base, make_dict_structure_fn(Base, converter))

converter.register_unstructure_hook(Derived, make_dict_unstructure_fn(Derived, converter)) 
converter.register_structure_hook(Derived, make_dict_structure_fn(Derived, converter))
# If Derive is registered before Base it works

data = { 'a': 1, 'b': 1.0, 'zz': 123 }
d = converter.structure( data, Derived )  # <-- raises StructureHandlerNotFoundError  Unsupported type: int. Register a structure hook for it.

d = Derived(a=1, b=1.0, zz=123)
data2 = converter.unstructure( d, Derived )  # <-- that never has problems. with or w/o PEP563 and both registration orders
```

**Comment by Tinche** [comment]
Interesting, I think I see the issue. It's a bug in attrs though. Let me create a writeup there.

**Comment by Tinche** [comment]
Actually this was already fixed in attrs as https://github.com/python-attrs/attrs/pull/843. You'll have to wait for a new release, which should be pretty soon.

**Comment by aha79** [comment]
I see. With your latest fixes on the main branch the above example now works with 'dataclass'.
So I could avoid attrs and use plain dataclasses (which is good for me)
