### ISSUE TITLE
the "latest" documentation changelog is outdated (declaring v1.9.0 as unreleased)

### ISSUE THREAD

**Issue by vlcinsky** [python-attrs/cattrs#204]
Clicking Changelog link on pypi https://cattrs.readthedocs.io/en/latest/history.html shows changelog, which declares v1.9.0 as unreleased while the latest released version is 1.10.0.

**Comment by Tinche** [comment]
Hm the docs build seems to be failing, investigating.

**Comment by Tinche** [comment]
I fixed the latest, not sure how to fix stable. Guess it'll fix itself when we make a new release.

**Comment by Tinche** [comment]
Thanks!
