### ISSUE TITLE
Allow passing tuple_factory to attr.astuple?

### ISSUE THREAD

**Issue by aldanor** [python-attrs/cattrs#21]
A simple suggestion: `attr.astuple` supports passing `tuple_factory` argument, so that you could, for instance, serialize attrs as lists:

```python
attr.astuple(Foo, tuple_factory=list)
```

This makes it nicer to work with some serializers (e.g. yaml) where you actually want a `list` and not a `tuple` since they may get serialized differently.

// There's also a few other useful arguments worth considering, e.g. `retain_collection_types`.

Maybe something like this would work?

```python
cattr.register_unstructure_hook(Foo, attr.astuple, tuple_factory=list)
```

**Comment by Tinche** [comment]
Hi,

you could maybe use:

    cattr.register_unstructure_hook(Foo, partial(attr.astuple, tuple_factory=list))

That should work today, if your unstructuring doesn't need to be recursive (attr.astuple obviously doesn't call back into your cattr converter).

**Comment by aldanor** [comment]
I meant the recursive unstructuring of course, sorry for not being clear (`attr.astuple` really being `cattr.unstructure_atttrs_fromtuple` or something like that, along the lines of what I mentioned in #20).

**Comment by Tinche** [comment]
This should be possible nowadays with the `unstruct_collection_overrides` argument to the GenConverter.
