### ISSUE TITLE
Fix and consolidate the docs on hook factories

### ISSUE THREAD

**Issue by bibajz** [python-attrs/cattrs#211]
* cattrs version:
* Python version:
* Operating System:

### Description

1. Final code example in https://github.com/python-attrs/cattrs/blob/main/docs/usage.rst#using-factory-hooks assumes the existence of `converter` instance and `to_camel_case` function defined above. Since a lot of code snippets on that page are abridged for brevity, would it make sense to duplicate their instantion / definition here too?
2. Also, shouldn't the `to_camel_case_(un)structure` functions have a `converter` parameter? Otherwise, they assume the global one defined above.

I propose the following  change to final code block:

```python
from functools import partial      
      
from attr import fields, has      
from cattr import Converter      
from cattr.gen import make_dict_structure_fn, make_dict_unstructure_fn, override      
      
converter = Converter()      
      
      
def to_camel_case(snake_str: str) -> str:      
    components = snake_str.split("_")      
    return components[0] + "".join(x.title() for x in components[1:])      
      
      
def to_camel_case_unstructure(cls, converter):                                                  
    return make_dict_unstructure_fn(      
        cls, converter, **{a.name: override(rename=to_camel_case(a.name)) for a in fields(cls)}      
    )      
      
      
def to_camel_case_structure(cls, converter):                                                  
    return make_dict_structure_fn(      
        cls, converter, **{a.name: override(rename=to_camel_case(a.name)) for a in fields(cls)}      
    )      
      
      
converter.register_unstructure_hook_factory(      
    has, partial(to_camel_case_unstructure, converter=converter)      
)      
converter.register_structure_hook_factory(      
    has, partial(to_camel_case_structure, converter=converter)      
)
```

Does it make sense or have I misunderstood the code example?

**Comment by Tinche** [comment]
For 1) I see your point, it makes it difficult to copy/paste the code. I would agree we could make the example complete by including everything.

For 2), you can write the functions as taking a converter (and passing it in when registering using functools.partial like you did) or write them as closures, capturing the converter (but it's missing in the example, like you mentioned). I went the closure route to keep it simpler, and since that's how I usually use it. So I would leave the closure style in.

It'd be great if you could submit a PR with the missing code in the last example.

**Comment by bibajz** [comment]
Ok, thank you for the explanation.

Indeed, the addition of `converter` parameter to examples (because the closure style is used in more places) together with the `partial` would probably obscure the ideas behind these hooks / structure funcs with too much stuff going on...

I will submit the PR with the final consolidated code block then.

Cheers,
Libor
