### ISSUE TITLE
Faster and more flexible structuring/unstructuring

### ISSUE THREAD

**Issue by Tinche** [python-attrs/cattrs#22]
Since people have started using cattrs, I've been getting more requests and contributions concerning faster and more flexible structuring/unstructuring.

We should start generating structuring/unstructuring functions for attrs classes, like recent releases of attrs generate hash and equality methods. This functionality should be then exposed directly to users.

I'm still unsure about the API.

For example, for a sample class:

```
@attr.s
class C:
    a: int = attr.ib()
    b: float = attr.ib()
```

a converter should be able to generate the following Python code:

```
def unstructure_dict_C(c):
    return {
        "a": c.a,
        "b": c.b,
    }

def structure_dict_C(dict_c, converter):
    return C(
        a=int(dict_c['a']),
        b=float(dict_c['b']),
    )
```
(this could get complex with generics, union and nested classes, so I've kept the example simple).

We could generate these on first contact with a class, and/or expose this directly to users so users can customize behavior:

```
cattr.register_unstructure_hook(C, cattr.gen.make_dict_unstructure(C, skip_defaults=True))
```

Bonus points if the generators could produce pieces of Python code along with functions, so we could generate complex structure/unstructure functions without calling back into the converter (since Python function calls are kinda expensive). Then cattrs could generate faster code than is generally written by hand.

**Comment by aldanor** [comment]
Just a little note, in the example above, it would be nice to be able to pass `dict_factory`, `filter` and `retain_collection_types` that `attrs` natively supports for serialization which would probably be propagated recursively downstream.

**Comment by Tinche** [comment]
This was done a long time ago ;)
