### ISSUE TITLE
Add `ExtraFieldsException`

### ISSUE THREAD

**Issue by vedantpuri** [python-attrs/cattrs#237]
* cattrs version: 22.1.0.dev0
* Python version: 3.7.5
* Operating System: macOS Monterey (12.2.1)

### Description
Trying to catch a specific exception for when extra fields are passed on the attrs class I am trying to construct. Right now the vanilla `Exception` is raised which I think should be made more specific.

### What I Did
See #236

**Comment by Tinche** [comment]
There's a PR to fix this: https://github.com/python-attrs/cattrs/pull/225

**Comment by vedantpuri** [comment]
Thats awesome!! Feel free to close this issue then, I haven't looked into the PR yet but it would be nice to make that Exception recursive too (so its easy to point to nested attrs classes when recursing through the exceptions)

**Comment by Tinche** [comment]
This is done!
