### ISSUE TITLE
The omit_if_default option is not working on float attributes defaulted to nan

### ISSUE THREAD

**Issue by jeffcarrico** [python-attrs/cattrs#242]
* cattrs version: 1.10.0
* Python version: 3.9.10
* Operating System: Linux

### Description

Trying to use omit_if_default to exclude float attributes that are initialized to nan.
I expected the attribute with the nan default to be omitted, but it was not.

Since nan is not equal to itself, are there any recommendations for how to handle this?

### What I Did

```python
import attrs
import cattrs
from typing import Optional


@attrs.define
class Test:
    x: float = float("nan")
    y: int = 0
    z: Optional[float] = None


converter = cattrs.GenConverter(omit_if_default=True)
t = converter.structure(dict(y=2), Test)
print(t) # Test(x=nan, y=2, z=None)
u = converter.unstructure(t)
print(u) # {'x': nan, 'y': 2}   <-- expected x to be omitted

x = float('nan')
x == x # False
```

**Comment by Tinche** [comment]
Ooph, yeah NaNs kinda suck. If it's just one class, you can simply write the unstructuring logic yourself and use it. Here's an example: https://replit.com/@TinTvrtkovic/cattrs242#main.py

If you need to be more generic, I can go into that as well.

**Comment by jeffcarrico** [comment]
This is very helpful thank you. I came up with this generalization which seems to work for my needs.

```python
import attrs
import cattrs
from typing import Optional
import math


@attrs.define
class Test:
    x: float = float("nan")
    y: int = 0
    z: Optional[float] = None


converter = cattrs.GenConverter(omit_if_default=True)
t = converter.structure(dict(y=2), Test)
print(t)  # Test(x=nan, y=2, z=None)
u = converter.unstructure(t)
print(u)  # {'x': nan, 'y': 2}   <-- expected x to be omitted

x = float("nan")
x == x  # False


def unstructure_test(t: Test) -> dict:
    res = {}
    for k, v in attrs.fields_dict(t.__class__).items():
        val = getattr(t, k)
        if v.type is float and math.isnan(v.default):
            if not math.isnan(val):
                res[k] = val
        else:
            if v.default != val:
                res[k] = val

    return res


converter.register_unstructure_hook(Test, unstructure_test)
print(converter.unstructure(t))
```

**Comment by Tinche** [comment]
GJ! I can help with making it more efficient if you ever have a need to.

**Comment by jeffcarrico** [comment]
Yes if there is a way to make this more efficient I'd like to hear it.

Also, is there a way to register this hook for multiple classes or any classes that I throw at converter.unstructure ? I feel like it is register_unstructure_hook_factory or register_unstructure_hook_func but I'm stumbling around trying to figure it out.

I guess I shouldn't have closed the issue. Thanks again!

**Comment by jeffcarrico** [comment]
I guess I could do this, right?
```python
converter.register_unstructure_hook(object, unstructure_test)
```

**Comment by Tinche** [comment]
`register_unstructure_hook` is the highest-level API but it won't be enough here. It's for when you want to register an existing hook for a particular class.

We need to use the most powerful API, `register_unstructure_hook_factory`. There are two big differences:
* it takes a predicate function instead of a class, giving us more power over when it's applied
* it has the ability to generate a specialized unstructuring function for every type.

You can read more about it [here](https://cattrs.readthedocs.io/en/latest/unstructuring.html#unstructuring-hook-factories).

First, we need a few helpers:
```python

def is_nan(x: float) -> bool:
    return x != x

def has_nan_defaults(type):
    """For a given class, is it an attrs class that also has a float with with a nan default?"""
    return attr.has(type) and any(a.type is float and is_nan(a.default)
                                  for a in attr.fields(type))
```

We can use `has_nan_defaults` as the predicate function.

We're going to use `cattrs.gen.make_dict_unstructure_fn`, which creates optimized unstructuring functions. We will wrap it and check each interesting field if the value produced is a NaN. If it is, we'll just remove it from the dictionary.

Here's the hook factory:
```python
def gen_float_unstructure(cl):
    """This is a factory, so it produces hook functions."""
    fn = make_dict_unstructure_fn(cl, converter)
    float_field_names = [
        a.name for a in attr.fields(cl)
        if a.type is float and is_nan(a.default)
    ]
    def unstructure_without_nans(instance):
        unstructured = fn(instance)
        for field_name in float_field_names:
            if is_nan(unstructured[field_name]):
                unstructured.pop(field_name)
        return unstructured
    return unstructure_without_nans
```

And then we just register it:
```python3
converter.register_unstructure_hook_factory(has_nan_defaults,
                                            gen_float_unstructure)
```

Here's the entire code: https://replit.com/@TinTvrtkovic/cattrs242#main.py.

**Comment by jeffcarrico** [comment]
Thank you, much appreciated. This worked great and is very helpful example for me to understand the pattern for creating these hooks.
