### ISSUE TITLE
cattrs fails on pypy

### ISSUE THREAD

**Issue by ygl-rg** [python-attrs/cattrs#253]
* cattrs version: 22.1
* Python version: 3.9.10 (Pypy 7.3.9)
* Operating System: Windows 10

### Description

cattrs fails to import.

raised error like this

TypeError: 'module' object is not iterable

in _compat.py, there is 

```python
  if "ExceptionGroup" not in __builtins__:
     from exceptiongroup import ExceptionGroup
  else:
    ExceptionGroup = ExceptionGroup
```

according to the pypy's doc https://doc.pypy.org/en/latest/cpython_differences.html

"the __builtins__ name is always referencing the __builtin__ module, never a dictionary as it sometimes is in CPython"

 so "if "ExceptionGroup" not in __builtins__" is invalid on pypy

### What I Did

```python
  import cattrs
```

**Comment by Tinche** [comment]
Fixed on `main`! Also reenabled the tests.

**Comment by mgedmin** [comment]
I suddenly started seeing this error in my daily GitHub action rebuilds.  Presumably GHA upgraded their PyPI images recently, since I've never seen this error before?

Do you have any plans to publish a PyPI release with the fix in the near future?

**Comment by Tinche** [comment]
Yep, it's in my queue!

**Comment by lloesche** [comment]
Ran into this issue today. A release version that works on PyPy would be very much appreciated.

**Comment by jpmckinney** [comment]
I added `'cattrs!=22.1.0;platform_python_implementation=="PyPy"'` to `install_requires`, which is kind of bananas, but it fixed CI for me.
