### ISSUE TITLE
converters are mutate despite deepcopy

### ISSUE THREAD

**Issue by GiorgioBalestrieri** [python-attrs/cattrs#260]
* cattrs version: 1.0.0
* Python version: 3.7
* Operating System: MacOS

### Description

When creating a `copy.deepcopy` of a cattrs `Converter` instance, and registering structure/unstructure hooks to the copy, the original `Converter` instance also ends up having those hooks, which isn't expected.

This makes it very hard to create specialized copies of a converter, or to make temporary changes to a converter for specific purposes.

### What I Did

```python
from cattr.converters import Converter
import copy
import attr

conv = Converter()

@attr.s(auto_attribs=True)
class A:
    x: int
    

def unstructure_a(a: A):
    # adding a message so that we can spot when the hook is being used
    print("using custom unstructure hook")
    return {"x": a.x}

other_conv = copy.deepcopy(conv)

other_conv.register_unstructure_hook(A, unstructure_a)

other_conv.unstructure(A(1))
# prints "using custom unstructure hook" (as expected)

conv.unstructure(A(1))
# prints "using custom unstructure hook" (unexpected)
```

To make this even more confusing, the two copies have different hashes:

```python
hash(conv) == hash(other_conv)
# returns False
```

**Comment by Tinche** [comment]
Yep, better copying is on the roadmap (possibly for the next version). It's been requested several times now.
