### ISSUE TITLE
`cattr.errors` shadows `cattrs.errors`

### ISSUE THREAD

**Issue by madig** [python-attrs/cattrs#263]
* cattrs version: 22.1.0
* Python version: 3.8.10
* Operating System: Windows x64

### Description

`cattr.errors` shadows `cattrs.errors`. This is relevant because I want to package structuring exceptions into a library exception. Or am I missing something here?

### What I Did

```
In [1]: import cattrs.errors

In [2]: cattrs.errors.BaseValidationError
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 cattrs.errors.BaseValidationError

AttributeError: module 'cattr.errors' has no attribute 'BaseValidationError'

In [3]: from cattrs.errors import BaseValidationError

In [4]:
```

**Comment by Tinche** [comment]
You're right, oops. Should be fixed on `main` though already, can you verify?

**Comment by madig** [comment]
Yes, it is, thanks. Sorry for the noise, didn't see an obvious entry in the changelog but didn't think of just testing master.

**Comment by Tinche** [comment]
No worries. I'm kind of in the middle of transitioning from `cattr` to `cattrs` (to follow `attrs`) so bugs like this sometimes happen.

**Comment by Tinche** [comment]
(`cattr` isn't going away, just not getting anything new.)
