### ISSUE TITLE
Way to access currently registered structure/unstructure hooks?

### ISSUE THREAD

**Issue by kmantel** [python-attrs/cattrs#269]
* cattrs version: 1.8.0
* Python version: 3.9.12
* Operating System: Ubuntu 20.04

### Description

For some classes, I just want to be able to add a slight parsing step on structure or unstructure, without worrying about whether a custom hook was registered or the default is used, and without rewriting all behavior for this hook. The idea for a new structure hook would be something like

1. do something small
2. do whatever is in the currently registered structure hook
3. register this as structure hook

I dug around and found I seem to be able to access the current hook for `cls` with `Converter._structure_func._function_dispatch.dispatch(cls)` - would there be any problems with using this or is there a better way to get access to it?

**Comment by Tinche** [comment]
Hello!

You should be able to just do `converter._structure_func.dispatch(cls)`; that should get you the registered hook, or if none is present it will generate a hook and return that.

It's technically an internal thing but I have no plans on changing it.
