### ISSUE TITLE
Recusivelly unstructuring nested objects only partially working

### ISSUE THREAD

**Issue by ericbn** [python-attrs/cattrs#274]
* cattrs version: 22.1.0
* Python version: 3.9.13
* Operating System: macOS 12.4

### Description

I have a set of classes auto generated by OpenAPI Generator, each one with a to_dict method that converts its objects to dicts. There's no base class to identify these classes with instanceof. In the example below, these are the [Filter](https://github.com/HubSpot/hubspot-api-python/blob/5f86e976338221d7ce26cc1413314a9ed72bbfe3/hubspot/crm/contacts/models/filter.py#L21) and [FilterGroup](https://github.com/HubSpot/hubspot-api-python/blob/5f86e976338221d7ce26cc1413314a9ed72bbfe3/hubspot/crm/contacts/models/filter_group.py#L21) classes from [hubspot-api-python](https://github.com/HubSpot/hubspot-api-python).

I want to recursively unstructure nested objects of these classes. Example:

```python
from datetime import datetime

from cattrs import Converter
from hubspot.crm.contacts import Filter, FilterGroup


converter = Converter()
converter.register_unstructure_hook(datetime, datetime.isoformat)
converter.register_unstructure_hook_func(
    lambda cl: callable(getattr(cl, "to_dict", None)),
    lambda d: d.to_dict(),
)

filter_group = FilterGroup(
    filters=[Filter(property_name="date", operator="LT", value=datetime(2022, 2, 1, 1, 0, 0, 0))]
)
converter.unstructure(filter_group)
```

This correctly gives me a dict with a list of dicts. But the datetime object is not converted to str as expected (as there's a corresponding unstructure hook registered).

I.e. I expected to get this:
```python
{
    "filters": [
        {"property_name": "date", "operator": "LT", "value": "2022-02-01T01:00:00"}
    ]
}
```
but got this instead:
```python
{
    "filters": [
        {"property_name": "date", "operator": "LT", "value": datetime(2022, 2, 1, 1, 0, 0, 0)}
    ]
}
```

### What I Did

I tried adding a recursive call to converter.unstructure in the hook func:
```diff
-    lambda d: d.to_dict(),
+    lambda d: converter.unstructure(d.to_dict()),
```
This gave me the expected results, but seems to be overkill, since the recursive unstructuring was already working for the other nested objects.

What am I missing?

**Comment by Tinche** [comment]
I imagine `to_dict()` has no knowledge of cattrs, so no surprise there. Given your hook factory, cattrs will just call it and return the results. When you register a hook, cattrs doesn't do any extra processing on the result; what gets returned from it is the final result.

As you've surmised, you can call unstructure additionally on the result of `to_dict` to apply cattrs rules; there's nothing wrong with that except that it's a little slow (since some work needs to be done twice). If that's no problem, you're done.

I see these classes are neither dataclasses not attrs classes; I don't know how tricky it would be to introspect them and prepare better hooks in advance.

**Comment by Tinche** [comment]
It's the `to_dict()` doing that, not cattrs, right?

**Comment by ericbn** [comment]
> It's the `to_dict()` doing that, not cattrs, right?

Oh yeah, that's it! `filter_group.to_dict()` already returns:
```python
{
    "filters": [
        {"property_name": "date", "operator": "LT", "value": datetime(2022, 2, 1, 1, 0, 0, 0)}
    ]
}
```

Now it all makes sense! Thanks a lot!  :- )

>  I don't know how tricky it would be to introspect them and prepare better hooks in advance.

BTW, these classes have an [`openapi_types` dict](https://github.com/HubSpot/hubspot-api-python/blob/5f86e976338221d7ce26cc1413314a9ed72bbfe3/hubspot/crm/contacts/models/filter.py#L35) mapping the attribute names to their types. Not sure how much of a desired feature it would be to have cattrs generally be able to use a dict like that to prepare better hooks in advance.

**Comment by Tinche** [comment]
I think the idea here would be for libraries like that to generate dataclasses/attrs classes and give you a prepared converter, rather than reinventing the wheel ;)

Anyway, ok to close?

**Comment by ericbn** [comment]
Thanks for the answers!  :- )
