### ISSUE TITLE
Inconsistent behavior between GenConverter and Converter

### ISSUE THREAD

**Issue by lpraat** [python-attrs/cattrs#292]
* cattrs version: 22.1.0
* Python version: 3.8.12
* Operating System: Ubuntu 22.04 LTS

### Description
From the documentation [here](https://cattrs.readthedocs.io/en/latest/cattrs.html#cattrs.converters.GenConverter) I read that GenConverter is just an alias of Converter. However, the behavior between the two is not consistent. In particular, Converter raises a cattrs.errors.StructureHandlerNotFoundError where GenConverter does not. Note that by swapping Block 1 and Block 2 in the code reported below (i.e., using GenConverter before Converter) no exceptions are raised.

### What I did
```python
import cattrs

from typing import List
from attrs import define


@define
class A:
    l: 'List[B]'

@define
class B:
    pass

# Using Converter -> KO, error
# -> Unsupported type: 'List[B]'. Register a structure hook for it.
converter = cattrs.Converter()
a = A([1,2,3])
try:
    converter.structure(converter.unstructure(a), A)
except cattrs.errors.StructureHandlerNotFoundError as e:
    print("Exception using Converter")
    print(e)
else:
    print("Converter Ok")

# Using GenConverter -> OK
converter = cattrs.GenConverter()
a = A([1,2,3])
try:
   converter.structure(converter.unstructure(a), A)
except cattrs.errors.StructureHandlerNotFoundError as e:
    print("Exception using GenConverter")
    print(e)
else:
    print("GenConverter Ok")

```

**Comment by Tinche** [comment]
You might be looking at the latest docs, in the version still up on PyPI `cattrs.Converter` is not (yet) `cattrs.GenConverter`. New release coming as soon as we work out some kinks.

**Comment by lpraat** [comment]
Ouch, my bad. Thank you!
