### ISSUE TITLE
Collection conversion not working with attrs

### ISSUE THREAD

**Issue by fightingdreamer** [python-attrs/cattrs#300]
* cattrs version: 22.1.0
* Python version: 3.10.6
* Operating System: MacOS 12.5.1

### Description

Seems like there are not way to setup generic collection conversion from `set` to `list`, when using `attrs` as item type in collection.

Here is my working example with exact type conversion(note: type comparison is error prone).

### What I Did

```python
from typing import Set

from attr import define, frozen
from cattrs import GenConverter


def test_set_unstructure_as_expected():
    @define
    class A:
        aa: Set[str]

    value = A({1, 2})
    expect = dict(aa={1, 2})

    converter = GenConverter(unstruct_collection_overrides={Set: list})
    assert converter.unstructure(value) == expect


def test_set_unstructure_should_work():
    @frozen(hash=True)
    class A:
        aa: str

    @frozen(hash=True)
    class B:
        bb: Set[A]

    value = B({A(1), A(2)})
    expect = dict(bb=[dict(aa=1), dict(aa=2)])

    converter = GenConverter(unstruct_collection_overrides={Set: list})
    assert converter.unstructure(value) == expect


def test_set_unstructure_workaround_with_exact_match():
    @frozen(hash=True)
    class A:
        aa: str

    @frozen(hash=True)
    class B:
        bb: Set[A]

    value = B({A(1), A(2)})
    expect = [
        dict(bb=[dict(aa=1), dict(aa=2)]),
        dict(bb=[dict(aa=2), dict(aa=1)]),
    ]

    converter = GenConverter()
    converter.register_unstructure_hook_func(
        lambda t: t == Set[A],
        lambda v: list(map(converter.unstructure_attrs_asdict, v)),
    )
    assert converter.unstructure(value) in expect
```

**Comment by Tinche** [comment]
I'm running this against the `main` branch, the only failing test is `test_set_unstructure_as_expected` and that's expected (the `expect` var needs to be `dict(aa=[1, 2])` instead). What's the exact problem?

**Comment by fightingdreamer** [comment]
I'm getting different results on stable 22.1.0:
```
PASS test_set_unstructure_as_expected
FAIL test_set_unstructure_should_work
PASS test_set_unstructure_workaround_with_exact_match
```

You are right about test_set_unstructure_as_expected, I made mistake there - changing `expect` to `dict(aa=[1, 2])` will make this test failing, after that correction I'm getting:

```
FAIL test_set_unstructure_as_expected
FAIL test_set_unstructure_should_work
PASS test_set_unstructure_workaround_with_exact_match
```

If it's already fixed in `main` branch, do you plan to push fixed version to pypi?

**Comment by Tinche** [comment]
Yeah, I plan on releasing next week after I've merged some stuff in. Give it a test on the main branch and see if it's good for you?
