### ISSUE TITLE
Python 3.11: it's  __notes__, not __note__

### ISSUE THREAD

**Issue by henryiii** [python-attrs/cattrs#301]
cattrs is using `__note__`, but it's actually `__notes__`, and a tuple of strings, and should be (python version conditionally) added via `.add_note(string)`, perhaps? (depending on the backport, I guess). `exceptiongroup` was updated in 1.0.0rc4, see https://github.com/agronholm/exceptiongroup/blob/main/CHANGES.rst.

Also, the message seems pretty poor on pytest + Python 3.10, is pytest and exceptiongroup clashing?

```pytb
      except Exception as e:
        e.__note__ = 'Structuring class Index @ attribute reply'
        errors.append(e)
>     if errors: raise __c_cve('While structuring Index', errors, __cl)
E     cattrs.errors.ClassValidationError: While structuring Index (1 sub-exception)

<cattrs generated structure scikit_build_core.file_api.model.index.Index>:19: ClassValidationError
```

(There's no more helpful err message below it, just that)

I tried running this outside of pytest, and it's much better, I can see the errors. But not inside pytest. I'm guessing it's the monkey patching warnings in https://pypi.org/project/exceptiongroup/. Maybe something to bring up with pytest? Or exceptiongroup? I think that might be https://github.com/agronholm/exceptiongroup/issues/23.

This is really cool when it works, though! (though the notes are missing, due to this issue, unless I force `exceptiongroup==1.0.0rc3`)

**Comment by Tinche** [comment]
You're right of course, but I don't think we need to support both versions. We should depend on the first exceptiongroup version to have `__notes__` and just use that (probably using __notes__ directly, to avoid the overhead of a method call ;). I would also be ok depending on the latest backport version, I don't think it's a huge burden on users to upgrade to it. Feel like making that PR?

As for pytest, I've noticed the same thing. It's probably on their end, not sure yet.

**Comment by henryiii** [comment]
Sure, I can.
