### ISSUE TITLE
Allow structuring None

### ISSUE THREAD

**Issue by phiresky** [python-attrs/cattrs#305]
* cattrs version:
* Python version: 3.10
* Operating System:

### Description

My code is doing this somewhere:

`cattrs.structure(None, types.NoneType)`

I'd expect this to return `None`, but instead it throws `Unsupported type: <class 'NoneType'>. Register a structure hook for it`

**Comment by klausmcm** [comment]
I'm using Python 3.7.3 so I don't have `types.NoneType`.

``` python
import cattrs

cattrs.register_structure_hook(type(None), lambda d, t: None)

cattrs.structure(None, type(None))
```

**Comment by Tinche** [comment]
Hi!

I don't think this is useful enough to include by default; I've never typed an attribute to be just `None`. But if you need it, it's one line away (thanks @klausmcm !).

Trying to keep cattrs more maintainable by avoiding having too many hooks ;)
