### ISSUE TITLE
Composition/nested classes

### ISSUE THREAD

**Issue by bitfinity** [python-attrs/cattrs#31]
* cattrs version:
0.6.0
* Python version:
3.6.4
* Operating System:
Mac os x/ubuntu 16.04/Python Alpine

### Description
I have @attrs classes using composition - i.e. class members are other @attrs classes. When I unstructure the top level object, there is no class information in the nested objects.
I can understand if this doesn't handle that, but there are many people who would like to do this, and the examples pointedly show only the simplest use cases and don't mention composition or nested classes at all, or inheritance.  I know there are hooks, but whether they are a good solution or this library is suitable for serializing and deserializing objects with inheritance or nesting is not clear.

### What I Did
Too much code, but I'd be happy to pm it.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by adrientetar** [comment]
> When I unstructure the top level object, there is no class information in the nested objects.

That's the whole point of cattrs, unstructure recursively turns classes into dict (so you can e.g. use json.dump on the result). What is the issue?

If you want just one-level dump you can use attr.asdict(), no need for cattrs.

**Comment by Tinche** [comment]
If I'm understanding this correctly, you'd like something like this:

```
@attr.s
class A:
    a = attr.ib()

>>> cattr.unstructure(A(1))
{
    "_type": "A",
    "a": 1
}
```
?

**Comment by bitfinity** [comment]
@Tinche , sorry this is what I have:

`
@attr.s
class CreateMixin:
    @classmethod
    def create_from_dict( cls, dict_: dict )->object:
        """ Called by parent class passing in dict.
        Used by following classes.
        Args:
            dict_ (dict):

        Returns: class

        """
        return cls(**dict_)

@attr.s
class ButtonAction(CreateMixin):
    """ Button action from slack interactions
    Attributes:
    name (str): name of action
    value (str): value of button (usually name, but sometimes number)
    type (str): I think button
    """
    name: str = attr.ib()
    value: str = attr.ib()
    type: str = attr.ib()

    @staticmethod
    def is_button( ljson ):
        """ Test for whether it is a button
        Args:
            ljson (dict): json that could be button

        Returns: bool

        """
        try:
            return ljson[ "actions" ][ 0 ][ "type" ]=="button"
        except (KeyError, IndexError):
            return False

@attr.s
class MenuAction(CreateMixin):
    """ Encapsulated slack interaction api menu action
    Attributes:
    name(str): name of menu
    selected_options(List[str]): which options are selected
    type(str): type of action
    value(str): we don't have multi-selects so one value stored
    """
    name: str = attr.ib()
    selected_options: List[ Any ] = attr.ib()
    type: str = attr.ib()
    value: str = attr.ib(init=False)

    def __attrs_post_init__( self ):
        """ These are initialized after the constructor"""
        self.value = self.selected_options

    @staticmethod
    def is_menu( ljson ):
        try:
            return ljson[ "actions" ][ 0 ][ "type" ]=="select"
        except (KeyError, IndexError):
            return False


@attr.s
class Team(CreateMixin):
    """ Encapsulates the team returned in json
    Attributes:
    id(str): team_id
    domain(str): email domain
    """
    id: str = attr.ib()
    domain: str = attr.ib()


@attr.s
class Channel(CreateMixin):
    """ Encapsulates the channel returned in interaction
    Attributes:
    id(str): channel id
    name(str): channel name
    """
    id: str = attr.ib()
    name: str = attr.ib()


@attr.s
class SlackUser(CreateMixin):
    """ Encapsulates slack user
    Attributes:
    id(str): slack id
    name(str): user's name
    """
    id: str = attr.ib()
    name: str = attr.ib()

@attr.s
class CommonCallback(Interaction):
    """ Common data to interaction api and slack events api
    Attributes:
    callback_id(str): the callback id assigned to the interaction
                    For multi-step interactions this is a str(guuid)
    action_ts(str): the timestamp of the interactio
    team(Team): team the user belongs to
    channel(Channel): the channel of the interaction (direct message)
    user(User): the user
    response_url(str): optional url to send future interactions to
    """
    callback_id: str = attr.ib()
    action_ts: str = attr.ib()
    team: Team = attr.ib(converter=Team.create_from_dict)
    channel: Channel = attr.ib(converter=Channel.create_from_dict)
    user: SlackUser = attr.ib(converter=SlackUser.create_from_dict)
    response_url: str = attr.ib()

    def __attrs_post_init__( self ):
        """ These are initialized after the constructor"""
        self.team_id = self.team.id
        self.channel_id = self.channel.id
        self.user_id = self.user.id


@attr.s
class DialogSubmission(CommonCallback):
    """ Dialog submission
    For some reason, the dialog api is completely different
    in its data format. Total pain.
    """
    submission: Dict = attr.ib()


    def __attrs_post_init__( self ):
        """ These are initialized after the constructor"""
        super().__attrs_post_init__()
        self.command = commands.get_command(self.type, self.callback_id)
        self.action_name = self.command.idname
        self.is_dialog = True
        self.action_value = self.submission

    @staticmethod
    def parse_is_dialog( ljson ):
        try:
            return ljson[ "type" ]=="dialog_submission"
        except (KeyError, IndexError):
            return False


@attr.s
class Callback(CommonCallback):
    """ Callback for Menu or button actions
    This object has what's in common with both

    Attributes:
    message_ts(str): message timestamp
    original_message: This is the last message. Used for updating
    the UI that a button was clicked.
    actions: Used in parsing for post init but discarded afterwards.
    Parsed into action field
    trigger_id(str): Used as required value to open a dialog
    action(Union[ButtonAction, MenuAction]): the action of the callback
    action_list(List): the list of actions (but we take one)
    """
    message_ts: str = attr.ib()             # message timestamp
    original_message: Dict = attr.ib()      # original message
    attachment_id: str = attr.ib()
    actions: List[Dict] = attr.ib()
    trigger_id: str = attr.ib()
    is_app_unfurl: Optional[str] = attr.ib(default=None)
    action: Union[ButtonAction, MenuAction] = attr.ib(init=False)
    action_list: List[ Union[ ButtonAction, MenuAction ]] = attr.ib(init=False)

    # @staticmethod
    # def serialize( ):
    #     import cattr


    def __attrs_post_init__( self ):
        """These items are initialized after constructor
        (because the default initialization isn't what we need)"""
        super().__attrs_post_init__()
        self.action_list = self.parse_actions(self.actions)
        if not self.action_list or len(self.action_list) == 0:
            raise ValueError("No actions")
        self.action = self.action_list[0]
        self.action_name = self.action.name
        self.command = commands.get_command(self.action_name, self.callback_id)
        self.actions = None
        self.is_menu = isinstance(self.action, MenuAction)
        self.is_button = isinstance(self.action, ButtonAction)
        self.action_value = self.action.value

    def _pre_serialize( self ):
        """We don't want to serialize this"""
        self.action_list = None

    # @property
    # def actions( self ):
    #     return self.action_objs

    @staticmethod
    def parse_actions( actions: List[ Dict ] ) -> List[ Union[ MenuAction, ButtonAction ] ]:
        """ Find out the kind of action we want
        Args:
            actions (List): from the list of action dicts, turn into
            Action objects

        Returns: List[Union[MenuAction, ButtonAction]]
        """
        action_objs = list()
        for action in actions:
            action_type = action.get( "type", "" )
            if action_type not in [ "select", "button" ]:
                raise ValueError( "None type or not select or button" )
            if action_type=="select":
                menu = MenuAction( **action )
                action_objs.append( menu )
            elif action_type=="button":
                button = ButtonAction( **action )
                action_objs.append( button )

        return action_objs

`

**Comment by Tinche** [comment]
Closing as stale.
