### ISSUE TITLE
Unstructuring of `enum.Enum` instances in `typing.Literal` types doesn't work

### ISSUE THREAD

**Issue by daniel-wer** [python-attrs/cattrs#321]
* cattrs version: 22.2.0
* Python version: 3.9.13
* Operating System: Ubuntu 20.04.1

### Description

I was glad to see https://github.com/python-attrs/cattrs/pull/231 which fixes the structuring of `enum.Enum` instances in `typing.Literal` types. However, the unstructuring doesn't work yet. See this example (adapted from https://github.com/python-attrs/cattrs/pull/231).

### What I Did

```python
import attr, cattrs, enum
from typing import Literal

class A(enum.Enum):
    BLA = 1

@attr.define
class Works:
    a: A

@attr.define
class Broken:
    a: Literal[A.BLA]

print(cattrs.unstructure(cattrs.structure({"a": 1}, Works)))   # {'a': 1}
print(cattrs.unstructure(cattrs.structure({"a": 1}, Broken)))  # {'a': <A.BLA: 1>}
```

My temporary fix is rather straightforward, but it would be great if cattrs would work for this out of the box:

```python
import cattrs
from typing import Literal, get_origin

_c = cattrs.GenConverter()
_c.register_unstructure_hook_func(lambda v: get_origin(v) is Literal, _c.unstructure)
```

**Comment by Tinche** [comment]
Sorry, for whatever reason I forgot to leave a comment when you created the issue.

You're right, I'll get this fixed for the next version.

**Comment by Tinche** [comment]
This got fixed in the meantime!
