### ISSUE TITLE
How to structure multiple fields into one attribute

### ISSUE THREAD

**Issue by vavanade** [python-attrs/cattrs#324]
### Description

for example I have a dict like this
```
my_unstructured_thing = {"name": "path/to/file", "extension": ".txt", "myint": 4}
```

and a class I want this dict to structure to

```
import attrs
import typing
import pathlib

MyPath = typing.NewType("MyPath", pathlib.Path)

@attrs.define
class MyThing:
    myint: int
    path: MyPath
```

I made the `MyPath` `NewType` so I can easily register hooks just for this case and not for all `pathlib.Path`s. But I don't know whether it is possible to make `cattrs` converter to convert the `name` and `extension` keys to one attribute.

Can it be done or do I have to preprocess the dict to merge the `name` and `extension` keys into a `path` key and go from there?

**Comment by Tinche** [comment]
Hello!

There's no built-in way to do this, you'll need to preprocess, but it's not hard. Here's a snippet:

```python
from pathlib import Path

import attrs

from cattrs import Converter
from cattrs.gen import make_dict_structure_fn


@attrs.define
class MyThing:
    myint: int
    path: Path


c = Converter()

c.register_structure_hook(Path, lambda v, _: Path(v))  # Register this first
struct_fn = make_dict_structure_fn(MyThing, c)


def my_struct_fn(val: dict, _) -> MyThing:
    val["path"] = val["name"] + val["extension"]
    return struct_fn(val, _)


c.register_structure_hook(MyThing, my_struct_fn)

print(c.structure({"name": "path/to/file", "extension": ".txt", "myint": 4}, MyThing))
```

You basically get the default structure fn and stick a small wrapper on it.

Good luck!

**Comment by Tinche** [comment]
Ah sorry I closed by accident, reopen if you have further issues!

**Comment by vavanade** [comment]
I don't. Thanks for the reply!

**Comment by vavanade** [comment]
Thanks a lot! The `make_dict_structure_fn` also solved another issue I was having and I was thinking about making an Issue here.
