### ISSUE TITLE
Support `type(None)` as well as `None`

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/cattrs#346]
* cattrs version: 23.1.0.dev0
* Python version: 3.11.1
* Operating System: Manjaro KDE

### Description

I wanted to be able to use `type(None)` as a structure target, as well as `None` itself, and have them both behave the same.

### What I Did

```py
from cattrs import Converter
c = Converter()

def structure(what, how):
    out = c.structure(what, how)
    assert isinstance(out, how), "Something went wrong"
    return out

# Usually, the following is valid:
structure("123", int)  # 123

# But I can't do it with `None`:
structure(None, type(None))  # cattrs.errors.StructureHandlerNotFoundError: Unsupported type: <class 'NoneType'>. Register a structure hook for it.
structure(None, None)  # TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

Cattrs doesn't support using `type(None)` as a structure target class, and Python doesn't support using `None` for instance checking.

**Comment by MicaelJarniac** [comment]
This issue might actually make no sense.

**Comment by Tinche** [comment]
Yeah, I'm not sure this is worth supporting. NoneType is somewhat esoteric, and you can add the hook yourself if you need it (I haven't so far).

**Comment by tovrstra** [comment]
For those who'd need to add support for `None` and `NoneType`, it can be implemented as follows. This was useful in  a code for (un)structuring return values of arbitrary functions, some of which returned `None`.

```python
from types import NoneType
cattrs.register_structure_hook(NoneType, lambda d, t: None)
cattrs.register_unstructure_hook(NoneType, lambda d: None)
```

**Comment by salotz** [comment]
This did come up for me when writing some union handling hook factories. E.g. looping over a set of types that can include None outside of an Optional.

I decided to just special case it in that code and not rely on another set of hooks being around, but in general I think it makes the whole type system "smoother" to not have to special case None in type reflection code.

Not a big deal, but +1 for just supporting out of the box. I don't see what it could hurt.
