### ISSUE TITLE
Allow overriding unstruct_collection_overrides in preconf make_converter

### ISSUE THREAD

**Issue by ericbn** [python-attrs/cattrs#350]
* cattrs version: 22.2.0
* Python version: 3.9.16
* Operating System: macOS

### Description

What I was trying to do:
```python
from collections.abc import Set

from cattrs.preconf.json import make_converter as json_make_converter

json_converter = json_make_converter(unstruct_collection_overrides={Set: sorted})
```

This didn't work because `cattrs.preconf.json.make_converter` overrides the `kwargs`: https://github.com/python-attrs/cattrs/blob/5ccd616cb9ae2ad88b5d4ba7816f7fad3a9f84be/src/cattrs/preconf/json.py#L40-L44

Then I tried:
```python
from collections.abc import Set

from cattrs.preconf.json import make_converter as json_make_converter

json_converter = json_make_converter().copy(unstruct_collection_overrides={Set: sorted})
```

But later in the code I call `json_converter.dumps` and mypy complained `error: "Converter" has no attribute "dumps"  [attr-defined]` because `copy` returns a `Converter`.

### What I Did
```python
from collections.abc import Set

from cattrs.preconf.json import JsonConverter
from cattrs.preconf.json import configure_converter as json_configure_converter

json_converter = JsonConverter(unstruct_collection_overrides={Set: sorted})
json_configure_converter(json_converter)
```

Maybe the two forms that I've tried above should also be allowed?

**Comment by Tinche** [comment]
Howdy,

I think it's an oversight.

Could you change the lines:

```python
kwargs["unstruct_collection_overrides"] = {
        **kwargs.get("unstruct_collection_overrides", {}),
        AbstractSet: list,
        Counter: dict,
    }
```
to
```python
kwargs["unstruct_collection_overrides"] = {
        AbstractSet: list,
        Counter: dict,
        **kwargs.get("unstruct_collection_overrides", {}),
    }
```
, add a small test and submit a PR?

**Comment by ericbn** [comment]
Hi. I'll work on a PR. Thanks for the quick response!
