### ISSUE TITLE
`cattrs.unstructure_attrs_asdict` is missing

### ISSUE THREAD

**Issue by AdrianSosic** [python-attrs/cattrs#358]
* cattrs version: 22.2.0  
* Python version: 3.8
* Operating System: macOS

### Description

It's just a minor issue, but I think `unstructure_attrs_asdict` is missing in the global namespace. While one can directly call `cattrs.structure_attrs_fromdict`, its unstructuring counterpart is missing (maybe there is a reason that I am not aware of?), which currently requires the following workaround:
```
converter = cattrs.global_converter
converter.unstructure_attrs_asdict(obj)
```

**Comment by Tinche** [comment]
You're right, but `cattrs.unstructure` will do the equivalent (not the same, since it uses the modern machinery). Or do you need the old function explicitly?

If so, I'll gladly take a small PR.

**Comment by AdrianSosic** [comment]
I’m not sure, actually… Maybe you can tell me? =)

I thought it is needed when registering hooks with the global converter, in order to avoid running into endless recursions, as described in #140?

**Comment by Tinche** [comment]
I feel like that's an advanced use case though. The global versions are there for convenience I'd say, if you're doing anything serious, making your own instance of a converter is the way to go.

Unless you feel strongly about it, I'm going to close this.

**Comment by AdrianSosic** [comment]
No, I’m fully OK with that. But for consistency reasons, I should probably still point out: its siblings `structure_attrs_from*` **are** available, which might confuse people (just like it confised me, initially). So, according to your logic, these should then be removed (unless there is an additional less special use case for them)? If this is not desired for backward compatibility, adding the corresponding unstructuring methods would  make the balance right. 

But I’m happy either way or with keeping the current state. So feel free to close, if you decide to keep things as they are.

**Comment by Tinche** [comment]
I'd love to remove em but it'll just cause pain to someone. I think keeping the status quo is the best we can do currently.
