### ISSUE TITLE
Recursive type definitions throws ClassValidationError

### ISSUE THREAD

**Issue by ares-b** [python-attrs/cattrs#361]
* cattrs version: 22.2.0
* Python version: 3.8.1
* Operating System: Ubuntu 22.04

### Description
Cannot structure a Data Class with a recursive attribute (attribute of type Self).
Throws a cattrs.errors.ClassValidationError.

### What I Did

```
import attrs
import cattrs
from typing import Union

@attrs.define
class MyClass:
    a: int
    test: Union["MyClass", None] = None

nested = {
    "a": 1,
    "test": {
        "a": 2,
        "test": {
            "a": 3
        }
    }
}
test = cattrs.structure(nested, MyClass) # Throws cattrs.errors.ClassValidationError

```

**Comment by Tinche** [comment]
Hi,

you need to wrap the **entire** type definition in strings here, like this:

```python
from typing import Union

import attrs

import cattrs


@attrs.define
class MyClass:
    a: int
    test: "Union[MyClass, None]" = None


nested = {"a": 1, "test": {"a": 2, "test": {"a": 3}}}
test = cattrs.structure(nested, MyClass)  # Throws cattrs.errors.ClassValidationError
```

If you feel like adding this to the docs somewhere, I'd be glad to merge.

**Comment by Tinche** [comment]
Another option is using `from __future__ import annotations` but that might be unavailable on 3.8? Not sure.
