### ISSUE TITLE
`AttributeError` during fetching `__orig_bases__` on non-generic protocol implementation.

### ISSUE THREAD

**Issue by nekitdev** [python-attrs/cattrs#374]
* cattrs version: 23.1.2
* python version: 3.11.3
* operating system: windows 11

### Description

I wanted to register an `unstructure` hook for an `Entity` type derived from the non-generic `Binary` protocol.

### What I Did

```python
CONVERTER.register_unstructure_hook(
    Entity, make_dict_unstructure_fn(Entity, CONVERTER, client_unchecked=override(omit=True))
)
```

Which caused an error:
```python
  File ".../cattrs/gen/__init__.py", line 82, in make_dict_unstructure_fn
    mapping = generate_mapping(cl, mapping)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../cattrs/gen/_generics.py", line 32, in generate_mapping
    orig_bases = cl.__orig_bases__
                 ^^^^^^^^^^^^^^^^^
AttributeError: type object 'Entity' has no attribute '__orig_bases__'
```

**Comment by Tinche** [comment]
Can you show me the `Entity` class? Or a minimal example of it that reproduces the issue.

**Comment by nekitdev** [comment]
Will do so a bit later, thanks for responding!

**Comment by nekitdev** [comment]
Here is an example I came up with; importing `Protocol` from `typing` does not change anything.
If the `Protocol` was generic, everything would work just fine.

```python
from attrs import define
from cattrs import Converter
from cattrs.gen import make_dict_unstructure_fn
from typing_extensions import Protocol

CONVERTER = Converter()


class SomeProtocol(Protocol):
    ...


@define()
class Entity(SomeProtocol):
    ...


CONVERTER.register_unstructure_hook(Entity, make_dict_unstructure_fn(Entity, CONVERTER))
```

**Comment by shadchin** [comment]
I have the same error :-(

**Comment by waweber** [comment]
Also seeing this error.

There's a couple workarounds I tried that seem to work:

Adding a no-op protocol as a base (this one might have unknown consequences):

```python
_T = TypeVar("_T", covariant=True)

class _Protocol(Protocol[_T]):
    ...

class SomeProtocol(_Protocol[Any], Protocol):
    ...


@define()
class Entity(SomeProtocol):
    ...
```

Adding a fake `__orig_bases__` attribute:

```python

class SomeProtocol(Protocol):

    __orig_bases__: ClassVar[tuple] = ()

    ...


@define()
class Entity(SomeProtocol):
    ...
```

**Comment by Tinche** [comment]
Alright, starting on this before wrapping up the next release.

I think the problem is `Protocol` is a subclass of `Generic`, even though it's not necessarily generic. Should be an easy fix.
