### ISSUE TITLE
Unstructure hook for `NewType` not invoked if `NewType` appears in a union

### ISSUE THREAD

**Issue by layday** [python-attrs/cattrs#380]
* cattrs version: 23.1.2
* Python version: 3.11
* Operating System: macOS

### Description

`NewType` unstructure hooks are not invoked if the new type appears in a union with other types.

### What I Did

```py
from typing import NewType

from attr import define
from cattr import Converter

Foo = NewType('Foo', str)

converter = Converter()
converter.register_unstructure_hook(Foo, lambda v: v.replace("foo", "bar"))

@define
class ModelWithFoo:
    total_foo: Foo
    maybe_foo: Foo | None

print(converter.unstructure(ModelWithFoo(Foo("foo"), Foo("is it a foo?"))))
# Produces: {'total_foo': 'bar', 'maybe_foo': 'is it a foo?'}
```

**Comment by Tinche** [comment]
You're right, our optional handling is very old and can be improved. Taking a look at it now.

**Comment by Tinche** [comment]
This should be fixed on main now, let me know!

**Comment by layday** [comment]
Yep, works now, thanks.

**Comment by layday** [comment]
Although, if I replace `| None` with e.g. `| bool`, it doesn't - not sure if that's intentional. String subclasses work with other kinds of unions.

**Comment by Tinche** [comment]
Yeah we don't support any union, just a subset for now. It's tricky to do well.
