### ISSUE TITLE
transform_error's format_exception parameter is not passed down recursively

### ISSUE THREAD

**Issue by oc-ben-ellis** [python-attrs/cattrs#389]
* cattrs version: 23.1.2 
* Python version: 3.10.9
* Operating System: WSL2 - Ubuntu

### Description

I'd expect when I call,

```python
transform_error(ex, format_exception=my_format_exception_handler)
```

I would expect `my_format_exception_handler` callable to be called and the return value applied to to all exceptions.

However, as it recursively calls itself without passing on the format_exception parameter, it uses the default format_exception callable instead of the one I passed in.

**Comment by Tinche** [comment]
Eep, you're right.

**Comment by BEllis** [comment]
> Eep, you're right.

@Tinche happy for this to be closed unless you normally wait for the release?

**Comment by Tinche** [comment]
Yeah we can close, I'll release in the next couple of weeks. Thanks!
