### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [python-attrs/cattrs#422]
Is it possible next time on release new version make the github release to have entry on https://github.com/python-attrs/cattrs/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release

**Comment by Tinche** [comment]
Sure, will do. Doing that easily was one of the reasons to switch to Markdown for documentation ;)

**Comment by kloczek** [comment]
Processing those notification's allows me to save some time save some time to initiate automated upgrade of the build procedures.
Thank you very much 👍 😄
