### ISSUE TITLE
NamedTuple to dictionary serialization

### ISSUE THREAD

**Issue by karlicoss** [python-attrs/cattrs#425]
* cattrs version: 23.1.2
* Python version: 3.10
* Operating System: Ubuntu 22.04

### Description

For my project, [cachew](https://github.com/karlicoss/cachew), I've been trying to switch from using my custom serialization cold to some existing library.
After some [evaluation](https://github.com/karlicoss/cachew/blob/master/doc/serialization.org#comparison), cattrs seems like the most promising since it works so well with python typing annotations.
One thing that stops me is that seems like it doesn't support `NamedTuple`? I feel like it should be treated just like a `@dataclass`, but seems like cattrs just treats them as 'unknown' types and leaves intact. 

### What I Did

This is kinda the minimal snippet that shows the issue:

```
from dataclasses import dataclass
from typing import NamedTuple

import cattrs

@dataclass
class D:
    value: int


class N(NamedTuple):
    value: int


und = cattrs.unstructure(D(value=123), D)
unn = cattrs.unstructure(N(value=123), N)

print(und, type(und))
print(unn, type(unn))
```

The result is

```
{'value': 123} <class 'dict'>
N(value=123) <class '__main__.N'>
```

So the dataclass is serialized just as expected, but the namedtuple is just left intact.

I searched in `cattrs` source code, and it seems like `NamedTuple` isn't mentioned at all -- so perhaps it was just forgotten rather than deliberately left out? 
I know I can implement a custom adapter, but feels like it makes sense to have them treated as dataclasses by default?

**Comment by Tinche** [comment]
Howdy,

I think it's a combination of nobody having asked for it and supporting libraries probably being able to handle named tuples natively.

Most of the time, output from cattrs is directly piped to another library, like orjson or msgpack, and those probably support named tuples already (since they are tuples)?

Although now that I think about it, the current approach is inadequate because it will not unstructure deeply. So yeah, agreed on it needing to be fixed. A little bit unsure on how to unstructure named tuples though, my first instinct would be to unstructure to lists (like ordinary tuples), not dicts.

**Comment by karlicoss** [comment]
Ah thanks, good to know! IMO they are more like `dataclass` rather than plain tuples since they are typed properly and have field names. But perhaps this could be configurable if people prefer 'legacy' behaviour for some reason.

**Comment by gorkaerana** [comment]
Sounds good! How about I give it a try in a PR and we take it from there?

**Comment by Tinche** [comment]
Go for it!

**Comment by Tinche** [comment]
Howdy, I've just merged https://github.com/python-attrs/cattrs/pull/491. This adds the namedtuples-as-tuples functionality to cattrs. I'll leave this issue open while other folks work on a strategy for namedtuples-as-dataclasses.

**Comment by gnzsnz** [comment]
this is fantastic!

do you plan a new release to include namedtuples?

**Comment by Tinche** [comment]
Yep, finishing it up now. The only thing left is to rework the readme

**Comment by gnzsnz** [comment]
> Yep, finishing it up now. The only thing left is to rework the readme

I know that I'm a pain in the ... but I'm looking forward to have namedtuples in cattrs.

I'm happy to contribute with any changes needed, just let me know.
