### ISSUE TITLE
Register multiple hooks for a class

### ISSUE THREAD

**Issue by isohedronpipeline** [python-attrs/cattrs#541]
* cattrs version: 23.2.3
* Python version: 3.10.12
* Operating System: Ubuntu-22.04
* attrs version: 23.2.0

I mentioned this at the end of [another ticket](https://github.com/python-attrs/cattrs/issues/535), but I thought it deserved its own issue.

I'd like to register multiple unstructure hooks to a class.  Specifically, I want to register subclasses and also omit defaults.

How can I combine this:
`include_subclasses(Toy, c, union_strategy=configure_tagged_union)`
with this:
`hook = make_dict_unstructure_fn(Toy, c, _cattrs_omit_if_default=True)`

Thanks :-)

Ben

**Comment by Tinche** [comment]
Hello!

Can you create your converter with `Converter(omit_if_default=True)`? That's the easiest way. If not we can brainstorm further.

**Comment by isohedronpipeline** [comment]
I think so!
Thanks Tin :-)

**Comment by Tinche** [comment]
Alright, closing this to keep the issue list more manageable ;)
