### ISSUE TITLE
Register Iterable instead of Sequence for dumps?

### ISSUE THREAD

**Issue by wsanchez** [python-attrs/cattrs#6]
I was looking at the code and noticed that in [`converters.py:38`](https://github.com/Tinche/cattrs/blob/master/cattr/converters.py#L38), you use a `Sequence` where an `Iterable` would work for more object types.

Looking at [`_dump_seq`](https://github.com/Tinche/cattrs/blob/master/cattr/converters.py#L147), all it does it iterate over the given `seq`, so no other change should be needed.

**Comment by Tinche** [comment]
Why not? Try making the change and if the tests pass, submit a PR and I'll take a look :)
