### ISSUE TITLE
Need ability to unstructure convert set to list

### ISSUE THREAD

**Issue by jacobg** [python-attrs/cattrs#92]
* cattrs version: latest
* Python version: 3.7
* Operating System: mac os

### Description

When the `attr.s` class contains a set attribute, the structure conversion leaves it as a set. This is the documented behavior, as described here:  https://cattrs.readthedocs.io/en/latest/structuring.html#sets-and-frozensets

The problem is that after calling `unstructure`, `json.dumps(d)` is not able to render json from it. Yes, we could write a custom json encoder to handle sets, but it would be great to rely on `unstructure` to encode it into a canonical dictionary format that can be serialized directly to json without any other conversions.  For example, the `animal-case` library can convert snake cased dictionary key names to camel case, but when its dictionary walker encounters a set, it can't handle it.

Can an option be added to convert to list, or perhaps the ability to override the default set conversion using a `register_unstructure_hook`?

**Comment by jacobg** [comment]
The `attrs` library itself seems to have a similar option when calling `attr.asdict`: `retain_collection_types`
https://www.attrs.org/en/stable/api.html#attr.asdict

**Comment by jacobg** [comment]
#22 related

**Comment by Tinche** [comment]
Can you register an unstructure hook for sets and just unstructure the attribute as a list?

**Comment by jacobg** [comment]
@Tinche Thanks, I ended up doing that. I initially though that approach wouldn't work, because it wasn't converting sets of custom types that themselves having a registered converter. But then I saw that's a separate issue: #48

**Comment by Tinche** [comment]
@isohedronpipeline That's because, in Python, `issubclass(Set[str], set)` doesn't return true (in fact, it raises an exception). So you'd need a more sophisticated hook (a predicate hook, to be exact).

However since this is a really common issue with serialization libraries, you can just do this:

```python
from typing import Set

from attrs import define

import cattrs


@define
class Lorem:
    ipsum: Set[str]


c = cattrs.Converter(unstruct_collection_overrides={Set: list})

unstructured_obj = c.unstructure(Lorem({"amet", "dolor"}))
print(type(unstructured_obj["ipsum"]))

unstructured_set = c.unstructure({"amet", "dolor"})
print(type(unstructured_set))
```

There's docs for this in _latest_: https://catt.rs/en/latest/indepth.html#customizing-collection-unstructuring

**Comment by Tinche** [comment]
@jacobg Actually I think the easiest way to go here (sorry for taking me 4 years to write it down) would be to use a preconf converter - they come with these hooks preinstalled. See https://catt.rs/en/latest/preconf.html#standard-library-json or maybe https://catt.rs/en/latest/preconf.html#orjson.

**Comment by Tinche** [comment]
The next version will also have support for fine-grained composition of hooks via wrapping hook factories, see here: https://catt.rs/en/latest/customizing.html#customizing-collections. So I'm going to close this now ;)
